### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by pfalcon** [ZigFisher/IPCam_monitor#1]
Re: http://ipcam.octonix.net/~rewm/0012175E1558/2018/11/05/23.15.jpg

Так ты че, на Осокорках? Надо бы пиво занести...

**Comment by ZigFisher** [comment]
Нэд ;)
Там только тестовые камеры стоят у партнёра http://www.facebook.com/octonix.net/

**Comment by pfalcon** [comment]
Эх... ;-)
